imports:
    - { resource: @ZephyrAdminCoreBundle/Resources/config/security.yml }	

framework:
    #esi:             ~
    translator:       { fallback: fr }
    default_locale:  fr
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    assets:
        base_path: ~
        packages:
            assetic:
                version: '1.2'
                version_format: '%%s?v=%%s'
                base_path: /assets/
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

assetic:
    debug:         "%kernel.debug%"
    node: /usr/local/bin/node
    use_controller: false
    #bundles:        [ZephyrAdminCoreBundle]
    read_from:            "%kernel.root_dir%/../web/assets"
    write_to:             "%kernel.root_dir%/../web/assets"
    java: /usr/bin/java
    filters:
        cssrewrite: 
            bin: /usr/local/bin/uglifycss
        uglifyjs2: 
            bin: /usr/local/bin/uglifyjs
        uglifycss: 
            bin: /usr/local/bin/uglifycss
        less: ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Core\CoreBundle\Entity\FosUser
    from_email:
        address:        no-reply@zephyrmedias.com
        sender_name:    webmaster
    resetting:
        token_ttl: 86400
    service:
        mailer: fos_user.mailer.default
        email_canonicalizer:    fos_user.util.canonicalizer.default
        username_canonicalizer: fos_user.util.canonicalizer.default
        token_generator:        fos_user.util.token_generator.default
        user_manager:           fos_user.user_manager.default
    registration:
        confirmation:
            enabled:    true

twig:
    globals:
       color: '["000000","Noir","13a0d5","Bleu ciel","d0d0d0","Gris pâle"]'
       language: %language%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm: 
        auto_generate_proxy_classes: true
#        auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true


stfalcon_tinymce:
        include_jquery: true
        tinymce_jquery: true
        selector: ".tinymce"
        language: %locale%
        theme:
            simple:
                file_browser_callback : 'elFinderBrowser'
                theme: "modern"
                plugins:
                     - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
                toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
                image_advtab: true
                templates:
                     - {title: 'Test template 1', content: 'Test 1'}
                     - {title: 'Test template 2', content: 'Test 2'}
            # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
            bbcode:
                 plugins: ["bbcode, code, link, preview"]
                 menubar: false
                 toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: tinymce4 # other choices are tinymce or simple
#            showhidden: false # defaults to false
 #           tinymce_popup_path: "asset[bundles/stfalcontinymce/vendor/tiny_mce/tiny_mce_popup.js]"
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            compression: false # enable if you configured the uglifycss and uglifyjs2 assetic filters and want compression
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        driver: LocalFileSystem
                        path: upload/medias
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

a2lix_i18n_doctrine:
    manager_registry: doctrine      

a2lix_translation_form:
    locale_provider: default       
    locales: [fr, en , ru , es , pt]          
    default_locale: fr             
    required_locales: [fr]         
    manager_registry: doctrine      
    templating: "A2lixTranslationFormBundle::default.html.twig"     

lexik_translation:
    fallback_locale: fr      # (required) default locale to use
    managed_locales: [fr, en ]    # (required) locales that the bundle have to manage , es , pt
    base_layout:     "LexikTranslationBundle::layout.html.twig" # layout used with the translation edition template
    use_yml_tree:    true    # if "true" we will print a nice tree in the yml source files. It is a little slower.
    grid_input_type: text     # define field type used in the grid (text|textarea)
    grid_toggle_similar: false  # if "true", on the grid if a locale colunm is shown/hidden then similar locales columns will be shown/hidden too.
                                    # so if the col "en" is shown/hidden all "en_XX" cols will be shown/hidden too. Not in the reverse order ("en_XX" clicked, no impact on "en")
                                     # When using propel, this can be used to specify the propel connection name
    resources_registration:
        type:                 database     # resources type to register: "all", "files" or "database"
        managed_locales_only: true    # will only load resources for managed locales
    auto_cache_clean: true           # set to true to make the bundle automatically clear translations cache files
#    auto_cache_clean_interval: 600     # The number of seconds to wait before trying to check if translations have changed in the database.

jms_i18n_routing:
    default_locale: fr
    locales: [fr, en ]
    strategy: prefix_except_default

a2lix_translation_form:
    locale_provider: default       
    locales: [fr, en ]          
    default_locale: fr             
    required_locales: [fr]         
    manager_registry: doctrine      
    templating: "A2lixTranslationFormBundle::default.html.twig"     

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

mopa_bootstrap:
    form: ~  # Adds twig form theme  support
    menu: ~  # enables twig helpers for menu

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
    less_filter: none # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
