imports:
    - { resource: @ZephyrAdminCoreBundle/Resources/config/security.yml }	

framework:
    #esi:             ~
    translator:       { fallback: fr }
    default_locale:  fr
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    assets:
        base_path: ~
        packages:
            assetic:
                version: '1.2'
                version_format: '%%s?v=%%s'
                base_path: /assets/
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


fos_user:
    user_class: ne0shad0w\ZephyrAdminCoreBundle\ZephyrAdminCoreBundle\Entity\FosUser

twig:
    globals:
#       color: '["000000","Noir","13a0d5","Bleu ciel","d0d0d0","Gris pâle"]'
       language: %language%
       theme : %front_theme%

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

mopa_bootstrap:
    form: ~  # Adds twig form theme  support
    menu: ~  # enables twig helpers for menu

