security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path:             fos_user_security_check
                default_target_path:            user_dispatch
                always_use_default_target_path: false
            logout:       
                target: fos_user_security_login
            anonymous:    true
            remember_me:
                 key:  "%secret%"
                 lifetime: 86400
                 path:     /
                 domain:   ~
                 user_provider: fos_userbundle

    access_control:
        - { path: ^/[^/]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin/dashboard/register, role: ROLE_ADMIN }
        - { path: ^/[^/]+/tableauDeBord, role: ROLE_USER }
        - { path: ^/[^/]+/register$, role: ROLE_ADMIN }
        - { path: ^/[^/]+/register/^, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/[^/]+/admin/, role: ROLE_ADMIN }
        - { path: ^/[^/]+/user/, role: ROLE_USER }
        - { path: ^/[^/]+/membre, role: ROLE_USER }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/dashboard/register, role: ROLE_ADMIN }
        - { path: ^/tableauDeBord, role: ROLE_USER }
        - { path: ^/register$, role: ROLE_ADMIN }
        - { path: ^/register/^, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/membre, role: ROLE_USER }
